# Generated by Django 2.2.1 on 2019-05-24 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heartbit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medecin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='heartbit.Medecin'),
        ),
    ]
